# Generated by Django 5.0.4 on 2024-04-10 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.IntegerField(unique=True, verbose_name='Номер теста')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Вопрос')),
                ('answer', models.TextField(choices=[('Yes', 'Да'), ('No', 'Нет')], null=True, verbose_name='Ответ')),
                ('level', models.PositiveBigIntegerField(blank=True, choices=[(1, 'Легкий'), (2, 'Средний'), (3, 'Сложный'), (4, 'Высший разум')], null=True, verbose_name='уровень сложности')),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.test')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('succes_rate', models.PositiveSmallIntegerField(default=0)),
                ('pass_number', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.test')),
                ('toughest_question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='test_app.question')),
                ('username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_app.user')),
            ],
        ),
    ]
